In [2]:
#using numpy to create an array using list
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [3]:
#creating an array using tuple
arr1 = np.array((1,2,3,4,5,6,7,8))
print(arr1)

[1 2 3 4 5 6 7 8]


In [5]:
#creating 0-D array or scalar array
arr2 = np.array(42)
print(arr2)

42


In [14]:
#creating 1-D array
arr3 = np.array([1,2,3,4,5,6])
print(arr3)
#check how many dimension it has
print(arr3.ndim)

[1 2 3 4 5 6]
1


In [15]:
#creating 2-D arrays
#2-D arrays are used as matrix and in tensor
arr4 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr4)
#check how many dimension it has
print(arr4.ndim)

[[1 2 3]
 [4 5 6]]
2


In [16]:
#creating 3-D arrays used in 3rd order tensor
arr5 = np.array([[[1,2,3], [4,5,6]], [[7,8,9],[10,11,12]]])
print(arr5)
#check how many dimension it has
print(arr5.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [17]:
#When the array is created, you can define the number of dimensions by using the ndmin argument.
arr6 = np.array([1,2,3,4,5], ndmin = 5)
print(arr6)

[[[[[1 2 3 4 5]]]]]
