## Basics of Numpy
NumPy, which stands for ‘Numerical Python’, is a library meant for scientific calculations. The basic data structure of NumPy is an array. A NumPy array is a collection of values stored together, similar to a list.<br/><br/>
#### Two different advantages that NumPy arrays have over lists:
1. Ability to operate on individual elements in the array without using loops or list comprehension
2. Speed of execution

#### Creating Numpy Arrays
There are two ways to create NumPy arrays, which are mentioned below:<br/>
a. By converting the existing lists or tuples to arrays using np.array<br/>
b. By initialising fixed-length arrays using the NumPy functions<br/>

The key advantage of using NumPy arrays over lists is that arrays allow you to operate over the entire data, unlike lists. However, in terms of structure, NumPy arrays are extremely similar to lists. If you try to run the print() command over a NumPy array, then you will get the following output:


[element_1  element_2  element_3…]

In [1]:
import numpy as np

In [2]:
#define a Numpy array
np_heights = np.array([74, 72, 73, 85, 90])

In [3]:
np_heights

array([74, 72, 73, 85, 90])

In [4]:
# Multiple height (NumPy array) with a scalar.
np_heights * 2.54

array([187.96, 182.88, 185.42, 215.9 , 228.6 ])

In [5]:
# Let's define two NumPy array and perform '+' operation on that.
np1 = np.array([1,2,3])
np2 = np.array([4,5,6])
np1 + np2

array([5, 7, 9])