In [1]:
import numpy as np

#### Task-1

In [8]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Task-2

In [9]:
print(np.ones(10, dtype=int))

[1 1 1 1 1 1 1 1 1 1]


#### Task-3

In [10]:
print(np.full(10, 6, dtype=float))

[6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]


#### Task-4

In [11]:
print(np.arange(1,17,5))

[ 1  6 11 16]


#### Task-5

In [12]:
print(np.arange(10,50,3))

[10 13 16 19 22 25 28 31 34 37 40 43 46 49]


#### Task-6: Given the below NumPy array, find the number of dimensions, shape, size and the data type. Print the results.

In [17]:
f = np.array([[1,2,3,4], [6,7,8,9], [10, 11, 12, 13]])
print(f.ndim)
print(f.shape)
print(f.size)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

2
(3, 4)
12
int32
4
48


#### Task-7:Use the below NumPy array to answer the following question:

In [18]:
arr1 = np.arange(1,26).reshape(5,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [19]:
## Question-1
arr1[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [22]:
## Question-2
arr1[-2, -1]

20

In [23]:
## Question-3
arr1[:3,1]

array([ 2,  7, 12])

In [31]:
## Question-4
arr1[:3,1].reshape((3,1))

array([[ 2],
       [ 7],
       [12]])

#### Task-8

- Hint: https://stackoverflow.com/questions/24303164/how-to-put-complex-into-a-numpys-array

In [32]:
np.arange(0,10, dtype = np.complex)

array([0.+0.j, 1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j,
       8.+0.j, 9.+0.j])

#### Task-9: Create a random numpy array of size 3*3 using function

In [33]:
np.random.random((3,3))

array([[0.17602141, 0.59716787, 0.87606188],
       [0.71327301, 0.01588355, 0.52302006],
       [0.59797973, 0.28928009, 0.47691925]])

#### Task-10: Use the numpy function to generate a random integer between 0 and 100

In [35]:
np.random.randint(0,100)

45

#### Task-11

In [38]:
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [39]:
np.linspace(0.01,1.0,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

#### Task-12

In [42]:
np.arange(0,63).reshape(3,3,7)

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]],

       [[42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62]]])

#### Task-13: Create the below array  without using concat function

In [43]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
b = np.arange(21,30)
b

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [45]:
c = np.arange(41,50)
c

array([41, 42, 43, 44, 45, 46, 47, 48, 49])

In [46]:
np.vstack([a,b,c])

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### Task-14: Hint: Concatenate

In [47]:
np.hstack([a.reshape(3,3), b.reshape(3,3), c.reshape(3,3)])

array([[ 1,  2,  3, 21, 22, 23, 41, 42, 43],
       [ 4,  5,  6, 24, 25, 26, 44, 45, 46],
       [ 7,  8,  9, 27, 28, 29, 47, 48, 49]])

#### Task-15

In [48]:
np.random.seed(1)
arr2 = np.random.random([3,3])
arr2

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01, 3.96767474e-01]])

In [49]:
# Question: Generate Eigen value and Eigen Vectors of the above matrix
np.linalg.eig(arr2)

(array([ 0.82539988, -0.21691527,  0.35206076]),
 array([[ 0.68744958,  0.74299249, -0.27657509],
        [ 0.38964259, -0.6539094 ,  0.02478992],
        [ 0.61285539,  0.14270479,  0.96067251]]))

#### Task-16:

In [50]:
np.random.seed(1)
arr3 = np.random.random([3,4])
arr3

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02, 1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01, 4.19194514e-01, 6.85219500e-01]])

In [51]:
## Question: Find the dot product between arr2 and arr3
np.dot(arr2, arr3)

array([[0.2796646 , 0.36696654, 0.13426343, 0.37507356],
       [0.18425358, 0.28108237, 0.06607719, 0.20539026],
       [0.28581211, 0.37986134, 0.23070827, 0.44759756]])

#### Task-17:

In [76]:
np.random.seed(1)
arr4 = np.random.random(5)
arr4

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
       1.46755891e-01])

In [80]:
## Question: Perfrom the dot product between arr4 transpose and arr4 and generate the below result


array([[1.73907352e-01, 3.00391164e-01, 4.76968156e-05, 1.26079336e-01,
        6.12004358e-02],
       [3.00391164e-01, 5.18867376e-01, 8.23869824e-05, 2.17777557e-01,
        1.05711863e-01],
       [4.76968156e-05, 8.23869824e-05, 1.30815988e-08, 3.45792328e-05,
        1.67851782e-05],
       [1.26079336e-01, 2.17777557e-01, 3.45792328e-05, 9.14049845e-02,
        4.43690860e-02],
       [6.12004358e-02, 1.05711863e-01, 1.67851782e-05, 4.43690860e-02,
        2.15372915e-02]])

#### Task-18:

In [52]:
np.random.seed(1)
arr5 = np.random.randn(10).reshape(2,5)
arr5

array([[ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763],
       [-2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038]])

- Hint: https://www.tutorialgateway.org/python-numpy-aggregate-functions/

In [53]:
# Question-1: Find the max value from the give array
arr5.max()

1.74481176421648

In [58]:
## Question-2: Find the mean row wise.
np.mean(arr5, axis = 0)

array([-0.33859667,  0.56652768, -0.64468933, -0.37696476,  0.30801863])

In [59]:
## Question-3: Find the sum column wise.
np.sum(arr5, axis = 1)

array([ 0.2768562 , -1.24826511])

#### Task-19: Create a null vector of size 10 but the fifth value which is 1

- Hint: https://stackoverflow.com/questions/44209368/how-to-change-a-single-value-in-a-numpy-array

In [61]:
Z = np.zeros(10)
Z[4] = 1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Task-20: Reverse a vector (first element becomes last)

In [62]:
Z = np.arange(50)
Z[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

#### Task-21: Create a 8x8 matrix and fill it with a checkerboard pattern

In [76]:
Z = np.zeros((8,8),dtype=int)
print(Z)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [77]:
Z = np.zeros((8,8),dtype=int)
Z[::2,1::2] = 1
Z[1::2,::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### Task-22: Given a 1D array, negate all elements which are between 3 and 8, in place

- Hint: https://www.journaldev.com/37898/python-numpy-where

In [85]:
Z= np.arange(10)
np.where([(Z>3) & (Z<8)], -Z, Z)

array([[ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9]])

#### Task-23: Write a NumPy program to sum of all the multiples of 3 or 5 below 100

- Hint: Filter the array using where, then use sum to find the sum

In [90]:
x = np.arange(1, 100)
prx[[(x%3==0) | (x%5==0)]].sum())

2318


<ipython-input-90-1e21d6a8ac5c>:2: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  print(x[[(x%3==0) | (x%5==0)]].sum())


#### Task-24: Write a NumPy program to convert a NumPy array into Python list structure

In [88]:
a = np.arange(1,10).reshape(3,3)
print(a)
a.tolist()

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

#### Task-25: Get the positions where elements of a and b match

In [89]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)